### PR TITLE
Fix some issues

### PR DESCRIPTION
**Pull request by allanburleson**
Someone needs to work on merging these.

### CODE REVIEW

**Comment by allanburleson** [comment]
We've both made improvements to fight(), so merging won't work.

**Comment by ghost** [comment]
I'm sorry, but I don't understand the problem...

**Comment by ghost** [comment]
What exactly changed?

**Comment by allanburleson** [comment]
I fixed bugs where the game would crash if you didn't type a complete command (such as "item" instead of "item whatevercommand"). This also happens in some places in your new "memory" mode.

**Comment by ghost** [comment]
Memory has no commands...

**Comment by allanburleson** [comment]
Like goto sleep.

**Comment by ghost** [comment]
That's the subconscience... you found it?, did you get to the sleep?

**Pull request closed without merging**
